### ISSUE TITLE
Fix spacing issues

### ISSUE THREAD

**Issue by dmattia** [johnmryan/scanner-cminor#1]
https://github.com/johnmryan/scanner-cminor/blob/00ca68889134c2ff5405df70189aac6ddab9d500/main.c#L52-L85

In this function alone, you make use of:
- two space indentation (L53)
- six space indentation (L54)
- seven space indentation (L58)
- eight space indentation (L57)
- negative eight space indentation (L77)
- fourteen space indentation (L56)

Please standardize on your fourteen space option.

**Comment by johnmryan** [comment]
Duly noted, I prefer to use different indentation to keep the reader of the code constantly on their toes. Appreciate the feedback though!
