### ISSUE TITLE
Fix error message

### ISSUE THREAD

**Issue by dmattia** [johnmryan/scanner-cminor#2]
https://github.com/johnmryan/scanner-cminor/blob/00ca68889134c2ff5405df70189aac6ddab9d500/main.c#L18

I was trying to run this program and got the message: "Please provide the correct number of arguments." I then spent hours asking Jeeves for the documentation on how many "the correct number" was, but could not find the number on any message boards.

Nobody was of great help on Stackoverflow: https://stackoverflow.com/questions/56452921/how-many-arguments-do-i-need-to-provide-to-the-scanner-cminor-binary

I'm wondering, how much time did you save by telling the user to use "the correct number" of args vs telling me how many I should actually use? Did it save you from having to count to two in your head?

Plz update to say "Please provide one argument", thanks.

**Comment by johnmryan** [comment]
Surprising, usually Jeeves knows all the correct numbers. 

Resolved by: https://github.com/johnmryan/scanner-cminor/commit/fd4294218f01a207dc191753f12fd08366f00233
